using NFramework.Core.CLI.Abstractions;

namespace NFramework.NFW.CLI;

/// <summary>
/// Main CLI application class. The Run method is source-generated by the core-cli package.
/// </summary>
[CliApplication("nfw")]
public sealed partial class NfwCliApplication(NfwCliApplicationOrchestrator orchestrator) : ICliApplication
{
    private readonly NfwCliApplicationOrchestrator _orchestrator = orchestrator;

    public int Run(string[] args)
    {
        return _orchestrator.Run(args);
    }
}
